format = '${hostname}${os}${username}${directory}${git_branch}${git_status}${shell}${character}'
right_format = '${sudo}${c}${python}${nodejs}${rust}${golang}${php}${docker_context}${memory_usage}${battery}${time}'
add_newline = false

[hostname]
ssh_only = false
ssh_symbol = '󱘖  '
style = 'bold bg:#00ffff fg:#090c0c'
format = '[░▒▓](#00ffff)[ $ssh_symbol$hostname]($style)'

[os]
format = '[ $symbol]($style)'
style = 'bold bg:#00ffff fg:#090c0c'
disabled = false

[os.symbols]
Arch = ' '
Gentoo = ' '
Ubuntu = ' '
Windows = ' '

[username]
style_root = '#ff0000'
style_user = '#a3aed2'
format = '[](fg:#00ffff bg:$style)[ $user](bold bg:$style fg:#090c0c)[](fg:$style bg:#769ff0)'
show_always = true

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path]($style)[](fg:#769ff0 bg:#394260)"
truncation_length = 3
truncation_symbol = "/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Nextcloud" = "󰅟"
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[shell]
bash_indicator = '󱆃 '
cmd_indicator = ' '
nu_indicator = '󰏌 '
powershell_indicator = ' '
pwsh_indicator = '󰨊 '
zsh_indicator = ' '
format = '[ $indicator]($style)'
style = 'white bold'
disabled = false

[nodejs]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
format = '[](fg:#244D70)[${symbol} ${pyenv_prefix}(${version})( \($virtualenv\))]($style)[](fg:#244D70)'
version_format = '${raw}'
symbol = ' '
style = 'bold bg:#244D70 fg:#FFDB67'

[sudo]
format = '[](fg:#F90F67)[$symbol]($style)[](fg:#F90F67)'
symbol = '󰌆 '
style = 'bold bg:#F90F67 fg:#000000'
disabled = false

[c]
format = '[](fg:#ffffff)[$symbol ($version(-$name))]($style)[](fg:#ffffff)'
version_format = '${raw}'
symbol = ' '
style = 'bold bg:#ffffff fg:#004482'

[memory_usage]
threshold = 0
format = '[](fg:#500679)[$symbol ${ram_pct}]($style)[](fg:#500679)([](fg:#2B0962)[󰘸  ${swap_pct}](bold bg:#2B0962 fg:#D1C2EA)[](fg:#2B0962))'
symbol = '󰍛 '
style = 'bold bg:#500679 fg:#E3C9F1'
disabled = false

[battery]
format = '[](fg:#061836)[$symbol $percentage](bg:#061836 fg:white)[](fg:#061836)'
[[battery.display]]
threshold = 100

[time]
format = '[](fg:#1d2230)[[  $time](fg:#a0a9cb bg:#1d2230)]($style)[](fg:#1d2230)'
use_12hr = false
time_format = "%T"
style = "bg:#1d2230"
disabled = false
