format = """
$hostname\
$os\
$username\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
$shell\
$character"""

right_format = """
$python\
[ ](fg:#1d2230)$time\
$nodejs\
$rust\
$golang\
$php
"""

add_newline = false


[hostname]
ssh_only = false
ssh_symbol = '󱘖  '
style = 'bold bg:#00ffff fg:#090c0c'
format = '[░▒▓](#00ffff)[ $ssh_symbol$hostname]($style)'

[os]
format = '[ $symbol]($style)'
style = 'bold bg:#00ffff fg:#090c0c'
disabled = false

[os.symbols]
Arch = ' '
Gentoo = ' '
Ubuntu = ' '
Windows = ' '

[username]
style_root = '#ff0000'
style_user = '#a3aed2'
format = '[](fg:#00ffff bg:$style)[ $user](bold bg:$style fg:#090c0c)[](fg:$style bg:#769ff0)'
show_always = true

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Nextcloud" = "󰅟"
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[shell]
bash_indicator = '󱆃 '
cmd_indicator = ' '
nu_indicator = '󰏌 '
powershell_indicator = ' '
pwsh_indicator = '󰨊 '
zsh_indicator = ' '
format = '[ $indicator]($style)'
style = 'white bold'
disabled = false

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
use_12hr = false
time_format = "%T"
style = "bg:#1d2230"
disabled = false
