" Install vim-plug if not found
if has('win32') 
  if empty(glob($USERPROFILE . '/vimfiles/autoload/plug.vim'))
    silent execute '!curl -fLo "'.$USERPROFILE.'/vimfiles/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  endif
elseif empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

" vim-plug
if has('win32')
  call plug#begin($USERPROFILE.'/vimfiles/bundle')
else
  call plug#begin('~/.vim/bundle')
endif
Plug 'lambdalisue/suda.vim'
Plug 'mhinz/vim-signify'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
"Plug 'airblade/vim-gitgutter'
call plug#end()

set backspace=indent,eol,start
set nowrap
let g:airline_powerline_fonts = 1
let g:suda_smart_edit = 1
