" Install vim-plug if not found
if has('win32') 
  if empty(glob($USERPROFILE . '/vimfiles/autoload/plug.vim'))
    silent execute '!curl -fLo "'.$USERPROFILE.'/vimfiles/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  endif
elseif empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

" vim-plug
if has('win32')
  call plug#begin($USERPROFILE.'/vimfiles/bundle')
else
  call plug#begin('~/.vim/bundle')
endif
if !has('win32')
  Plug 'lambdalisue/suda.vim'
endif
Plug 'mhinz/vim-signify'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'chrisbra/unicode.vim'
Plug 'elkasztano/nushell-syntax-vim'
if has('win32')
  Plug 'vim-airline/vim-airline-themes' "airline looks like garbage on windows
endif
"Plug 'airblade/vim-gitgutter'
call plug#end()

set backspace=indent,eol,start
set nowrap
let g:airline_powerline_fonts = 1
let g:suda_smart_edit = 1
if has('win32')
  let g:airline_theme='base16_google'
endif

if !has('gui_running')
  set mouse-=a
endif
