# start the x server if we're on tty0 and nothing is running
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

# Bring "xterm" up to "xterm-256color", fairly well expected this should work
[[ "$TERM" == "xterm" ]] && export TERM="xterm-256color"

# make sure antigen exists
if [[ ! -a ~/.antigen.zsh ]]; then
  wget https://git.io/antigen -O ~/.antigen.zsh
fi

# powerlevel9k config
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status root_indicator context dir virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs)
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_VIRTUALENV_BACKGROUND=028

# Host-specific configuration
if [[ "$HOST" == 'hyrrokkin' ]]; then
  POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND=051
  POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=051
  POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=000
  POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=000
elif [[ "$HOST" == 'phoebe.node.tty.sh' ]]; then
  POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=201
  POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=201
  POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=000
  POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=000
fi

# load in antigen
source ~/.antigen.zsh

# pull in oh-my-zsh
antigen use oh-my-zsh

# plugins from oh-my-zsh
antigen bundle git
antigen bundle pipenv

# plugins from other repos
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

# set the theme
#antigen theme agnoster
antigen theme bhilburn/powerlevel9k powerlevel9k

# finish up
antigen apply

# Preferred Editor
export EDITOR="vim"

# commands aliases
alias svim="sudoedit"
alias unlock="gpg -o /dev/null -s /dev/null"
